game = ""
dynamic_ip_api = ""

#message token
pushplus_token = ""

max_sleep_time = 600
min_sleep_time = 180
request_retry_warning_num = 10
request_retry_stop_num = 20

sell_order_data_dir = ""
bill_order_data_dir = ""
buy_order_data_dir = ""